# Generated by Django 5.2 on 2025-04-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_order_order_items_cartitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
